name: ai
channels:
  - defaults
dependencies:
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.05.30
  - certifi=2023.5.7
  - cffi=1.15.1
  - contourpy=1.0.5
  - cryptography=39.0.1
  - cycler=0.11.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - icu=58.2
  - idna=3.4
  - intel-openmp=2023.1.0
  - jpeg=9e
  - kiwisolver=1.4.4
  - krb5=1.19.4
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang13=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libiconv=1.16
  - libogg=1.3.5
  - libpng=1.6.39
  - libtiff=4.5.0
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.10.3
  - libxslt=1.1.37
  - lz4-c=1.9.4
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - munkres=1.1.4
  - numexpr=2.8.4
  - numpy-base=1.25.0
  - openssl=1.1.1u
  - pandas=1.5.3
  - pcre=8.45
  - pillow=9.4.0
  - pip=23.1.2
  - ply=3.11
  - pycparser=2.21
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - python=3.11.4
  - python-dateutil=2.8.2
  - pytz=2022.7
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - selenium=3.141.0
  - setuptools=67.8.0
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.2
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.38.4
  - win_inet_pton=1.1.0
  - xz=5.4.2
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==1.4.0
      - asgiref==3.7.2
      - astunparse==1.6.3
      - cachetools==5.3.1
      - charset-normalizer==3.2.0
      - django==4.2.3
      - flatbuffers==23.5.26
      - gast==0.4.0
      - google-auth==2.21.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.56.0
      - h5py==3.9.0
      - image==1.5.33
      - keras==2.13.1
      - libclang==16.0.0
      - markdown==3.4.3
      - markupsafe==2.1.3
      - numpy==1.24.3
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - packaging==23.1
      - protobuf==4.23.4
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - sqlparse==0.4.4
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.1
      - tensorflow==2.13.0
      - tensorflow-estimator==2.13.0
      - tensorflow-intel==2.13.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==2.3.0
      - typing-extensions==4.5.0
      - tzdata==2023.3
      - urllib3==1.26.16
      - werkzeug==2.3.6
      - wrapt==1.15.0
